# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_tree}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Parrish"]
  s.date = %q{2010-08-02}
  s.description = %q{A MongoMapper plugin that adds a number of tree strategies.}
  s.email = %q{mtparrish@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "lib/mongo_tree.rb",
     "lib/mongo_tree/base.rb",
     "lib/mongo_tree/children.rb",
     "lib/mongo_tree/strategies/ancestor_array.rb",
     "lib/mongo_tree/strategies/child_link.rb",
     "lib/mongo_tree/strategies/full_tree_node.rb",
     "lib/mongo_tree/strategies/full_tree_root.rb",
     "lib/mongo_tree/strategies/materialized_path.rb",
     "lib/mongo_tree/strategies/parent_link.rb",
     "test/helper.rb",
     "test/test_mongo_tree.rb"
  ]
  s.homepage = %q{http://github.com/parrish/mongo_tree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A MongoMapper plugin that adds a number of tree strategies.}
  s.test_files = [
    "test/helper.rb",
     "test/test_mongo_tree.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.8.2"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0.8.2"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0.8.2"])
  end
end

